# -*- coding: utf-8 -*-
"""pyprg-shu-2020-spring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mUZrfVTsL6kR4PX41fCeDzEerBfeJe5-

# Python 程式設計 | 世新大學 2020 春季班

<https://www.sli.do>: X598

郭耀仁 tonykuoyj@gmail.com

## 2020-03-13
"""

# hello.py
print("Hello World!")

# zen.py
import this

"""## 2020-03-20"""

# input "03-19-2020"
# output "03-19-2020.csv"
#import requests
import pandas as pd

def get_covid_daily_data(input_date):
    csv_name = input_date + ".csv"
    github_url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/{}".format(csv_name)
    #response = requests.get(github_url)
    df = pd.read_csv(github_url)
    # df.head()
    # df.tail()
    df.to_csv(csv_name, index=False)

user_input = input("Please input a date(mm-dd-yyyy):")
get_covid_daily_data(user_input)

from datetime import date, timedelta

start_date = date(2020, 1, 22)
#time_delta = timedelta(57)
#end_date = start_date + time_delta
date_period = [start_date + timedelta(i) for i in range(58)]
data_dates = [i.strftime('%m-%d-%Y') for i in date_period]
for dt in data_dates:
    print("Downloading {}.csv...".format(dt))
    get_covid_daily_data(dt)

56_cannot_die = '五六不能亡'

cannot_56_die = '五六不能亡'
print(cannot_56_die)

cannot_die_56 = '五六不能亡'
print(cannot_die_56)

56_cannot_die = '五六不能亡'
print(56_cannot_die)

for = "For"

True = 1

print = 5566

movie_title = "Avengers: Endgame"
print(movie_title)

print = 5566
del print

movie_title = "Avengers: Endgame"
print(movie_title)

help(abs)

help(all)

my_object = 5566
print(my_object)

my_str = '5566'
print(my_str)

print(my_object**2)

print(my_str**2)

print(type(my_object))
print(type(my_str))

movie_title = "Avengers: Endgame"
movie_length = 181
movie_rating = 8.4

print(movie_title)
print(movie_length)
print(movie_rating)

print(type(movie_title))
print(type(movie_length))
print(type(movie_rating))

"""## 2020-03-27"""

movie_title = "陽光普照"
movie_rating = 7.7
movie_time = 156

print(movie_title)
print(movie_rating)
print(movie_time)

print(type(movie_title))
print(type(movie_rating))
print(type(movie_time))

help(print)

help(type)

current_celsius = 28
current_fahrenheit = current_celsius * 9 / 5 + 32
print(current_fahrenheit)

current_celsius = (current_fahrenheit - 32) * 5 / 9
print(current_celsius)

shaq_height = 216
shaq_weight = 147
shaq_bmi = shaq_weight / (shaq_height / 100) ** 2
print(shaq_bmi)

movie_title = "陽光普照"
print(movie_title)
print(type(movie_title))

movie_rating = 7.7
print(movie_rating)
print(type(movie_rating))

movie_time = 156
print(movie_time)
print(type(movie_time))

movie_story_line = """A Sun follows a troubled family of four. A-Ho, the younger son, has always been a problematic child, and his father, A-Wen has invested all his hopes and expectations in his introverted eldest son, A-Hao. While A-Hao is trying to get into medical school, A-Ho faces juvenile detention for a crime committed with his best friend - although not entirely of his own will. A-Wen abandons A-Ho, refusing to help and even requesting the judge to sentence his son as harshly as possible. Not long after A-Ho is sent to prison, to make matters worse, his girlfriend shows up on his mother Qin's doorstep. The teenage girl is pregnant and determined to have A-Ho's child, even though he is locked up and has no idea she is expecting. Written by Toronto International Film Festival"""
print(movie_story_line)
print(type(movie_story_line))

mcd = "I'm lovin' it!"
print(mcd)

ross_said = """Let's put aside the fact that you "accidentally" pick up my grandmother's ring."""
print(ross_said)

print(movie_title)
print(movie_rating)
print(movie_time)

print("{}的評分為：{} , 片長為{}分鐘".format(movie_title, movie_rating, movie_time))

movie_title = ("請輸入電影的名稱")
movie_rating = ("請輸入電影的評等")

print(movie_title)
print(movie_rating)

movie_title = input("請輸入電影名稱：")
movie_rating = input("請輸入電影評分：")
print("{}的評分為：{}".format(movie_title, movie_rating))

place = input("地點:")
weather = input("天氣:")

print("我在{}：天氣{}".format(place, weather))

print(True)
print(False)

print(type(True))
print(type(False))

id_last_digit = 7
print(id_last_digit % 2 == 1)











