# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1172gz975cBWPk6oUwsEw0jubW9omd7lm
"""

member_ages = [18, 20, 22, 25, 35, 42, 65]
# 資料篩選(begin)
list(filter(lambda x: x <= 25 and x >= 18, member_ages))

if True:
    print(5566)
print(7788)

if False:
    print(5566)
print(7788)

movie_title = input('請輸入電影的名稱:')
movie_rating = input('請輸入電影的評等:')
movie_rating = float(movie_rating)

if movie_rating > 7:
    print("{}的評分為 {} 分值得去看!".format(movie_title, movie_rating))
if movie_rating <= 7:
    print("{}的評分為 {} 分不值得去看，浪費時間!".format(movie_title, movie_rating))

monthly_income = int(input("請輸入月薪"))
saving_account = int(input("請輸入存款"))

if monthly_income > 40000:
    ans = "發放信用卡"
if saving_account >= 500000:
    ans = "發放信用卡" 
print(ans)

user_int = input("請輸入一個正整數")
user_int = int(user_int)
if user_int % 2 == 0:
    ans = "偶數"
if user_int % 2 == 1:
    ans = "奇數"
print(ans)

id_last_digit = input("請輸入您身分證字號的尾數")
id_last_digit = int(id_last_digit)
if id_last_digit % 2 == 0:
    ans = "星期二四六日領"
if id_last_digit % 2 == 1:
    ans = "星期一三五日領"
print(ans)

id_number = input("請輸入身份證字號")
id_last_digit = id_number[-1]
id_last_digit = int(id_last_digit)
if id_last_digit % 2 == 0:
    ans = "星期二四六日領"
if id_last_digit % 2 == 1:
    ans = "星期一三五日領"
print(ans)

height = float(input("請輸入身高(M)"))
weight = float(input("請輸入體重(KG)"))
bmi = weight / (height*0.01)**2
if bmi > 30:
    label= "Obese"
elif bmi > 25:
    label = "Overweight"
elif bmi > 18.5:
    label = "Normal weight"
elif bmi <= 18.5:
    label = "Underweight"
print(label)